on: 
  push:
    branches:
      - 'feature/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v4
    - name: Setup Python 3.11
      uses: actions/setup-python@v5
      with: 
        python-version: 3.11
    - name: Install dependencies 
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Lint with flake 8 
      run: | 
        pip install flake8
        flake8 .
    - name: Test with pytest
      run: | 
        pip install pytest
        pytest
  
