on: 
  pull_request: 
    branches: 
      - main
    types: [opened, synchronize]

jobs: 

  release-checks:

    if: startsWith(github.head_ref, 'release/')

    runs-on: ubuntu_latest

    steps: 
      - uses: actions/checkout@@v3
      - name: Build package
        run: | 
          python setup.py sdist
      - name: Publish package 
        uses: pypa/gh-action-pypi-publish@master
        with: 
          password: ${{ secrets.PYPI_API_TOKEN }}

